(() => {
'use strict';
const STORE='RWD_BA001_REDLINE_PREUPLOAD_V2';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const uid=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>'$'+Number(n||0).toFixed(2); const today=()=>new Date().toLocaleString();
const THEMES=['steel','neon','copper','arctic','redline','forest','graphite','sunset','hivis','blueprint'];
const base={view:'home',theme:'steel',settings:{shop:'Rolling Wrench Diesel',phone:'260-502-6222',laborRate:135,serviceCall:250,tax:0,markup:10},active:{customer:'',unit:'',vin:''},customers:[],units:[],parts:[],kits:[],quotes:[],workorders:[],invoices:[],ocr:[],schedule:[],pm:[],memory:[],pins:[],sync:[],clocks:{A:{name:'Job A',sec:0,run:false,start:0},B:{name:'Job B',sec:0,run:false,start:0},C:{name:'Job C',sec:0,run:false,start:0}}};
let st=load();
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k])merge(a[k],b[k]);else a[k]=b[k]}return a}
function load(){try{return merge(structuredClone(base),JSON.parse(localStorage.getItem(STORE)||'{}'))}catch{return structuredClone(base)}}
function save(){localStorage.setItem(STORE,JSON.stringify(st))}
function toast(t){const e=$('#toast'); e.textContent=t; e.className='toast show'; clearTimeout(window.__t); window.__t=setTimeout(()=>e.className='toast',1600)}
function nav(v){st.view=v; save(); render(); scrollTo(0,0)}
function applyTheme(){document.body.className='theme-'+(THEMES.includes(st.theme)?st.theme:'steel')}
const modules=[
 ['vin','CORE','VIN Decode','Decode VIN, save unit, send to parts'],['parts','CORE','Parts Lookup','By VIN, ESN, part number, OCR'],['kits','CORE','PM / Filter Kits','Filter kits and job parts kits'],['ocr','CORE','OCR Intake','Receipts, labels, VIN plates, notes'],
 ['customers','SHOP','Customers','Customer records and history'],['units','SHOP','Trucks / Equipment','VIN, engine, transmission, notes'],['quotes','MONEY','Quotes','Professional quote builder'],['workorders','SHOP','Work Orders','Approved jobs and labor'],['invoices','MONEY','Invoices','Invoice, print, signature'],
 ['clock','OPS','Time Clock','A / B / C job clocks'],['schedule','OPS','Schedule','Appointments and reminders'],['pm','OPS','PM Tracking','Intervals and reminders'],['gps','OPS','GPS Calls','Location pins and mileage'],['memory','OPS','Repair Memory','Saved repairs and parts notes'],['fault','SOON','Fault Doctor','Under construction'],['settings','SYSTEM','Settings','Shop rates, themes, backup']
];
function shell(content){return `<header class="header no-print"><div class="head-inner"><div class="brand"><div class="brand-mark">RW</div><div><h1>${esc(st.settings.shop)} BA001</h1><p>${esc(st.active.customer||'No active customer')} • ${esc(st.active.unit||'No active unit')}</p></div></div><div class="status"><span class="pill">VIN + PARTS BUILD</span><span class="pill">SHOP SCOPE</span><span class="pill">TOOLS ONLY</span></div></div></header><main class="shell">${content}</main><nav class="bottom-nav no-print"><div class="bottom-inner">${[['home','Home'],['vin','VIN'],['parts','Parts'],['kits','Kits'],['settings','Settings']].map(x=>`<button data-nav="${x[0]}" class="${st.view===x[0]?'active':''}">${x[1]}</button>`).join('')}</div></nav>`}
function render(){applyTheme(); $('#app').innerHTML=shell((pages[st.view]||pages.home)()); bind();}
function tile(m){return `<button class="tile" data-nav="${m[0]}"><span class="tag">${m[1]}</span><b>${m[2]}</b><span>${m[3]}</span></button>`}
const pages={
home(){return `<section class="hero"><div class="card"><h2>VIN, Parts, Kits, Jobs.</h2><p class="muted">A cleaner BA001 layout with CSS-only themes. No theme images required, no icon libraries required, and no broken theme graphics.</p><div class="actions"><button class="btn primary" data-nav="vin">Start VIN Decode</button><button class="btn" data-nav="parts">Find Parts</button><button class="btn" data-nav="kits">Build Kit</button><button class="btn" data-nav="ocr">OCR Intake</button></div></div><div class="card"><p class="muted">Active VIN</p><div class="money">${esc(st.active.vin||'None')}</div><p class="muted">${st.customers.length} customers • ${st.units.length} units • ${st.parts.length} parts • ${st.quotes.length} quotes</p></div></section><section class="grid">${modules.map(tile).join('')}</section>`},
vin(){return module('VIN Decode Center',`<div class="form"><label>VIN<input id="vin" maxlength="17" value="${esc(st.active.vin)}" placeholder="17 character VIN"></label><label>Unit Name / Truck #<input id="unit" value="${esc(st.active.unit)}" placeholder="Truck #4, W900, Trailer 12"></label><label>Customer<input id="customer" value="${esc(st.active.customer)}"></label><label>Engine / ESN<input id="engine"></label><label>Transmission<input id="trans"></label><label>Mileage / Hours<input id="miles"></label><label class="full">Notes<textarea id="notes" placeholder="PTO, dump truck, glider, axle info, engine serial, etc."></textarea></label></div><div class="actions"><button id="decode" class="btn primary">Decode VIN</button><button id="saveUnit" class="btn ok">Save Unit</button><button id="vinToParts" class="btn">Use VIN For Parts</button></div><div id="vinOut" class="records"></div>`+list('units'))},
parts(){return module('Parts Lookup',`<div class="form"><label>VIN<input id="partVin" value="${esc(st.active.vin)}"></label><label>Engine / ESN<input id="partEngine"></label><label>Part Number<input id="pn" placeholder="OEM or aftermarket number"></label><label>Description<input id="pdesc" placeholder="water pump, wheel seal, clutch, filter"></label><label>Qty<input id="pqty" type="number" value="1"></label><label>Cost<input id="pcost" type="number" step="0.01"></label><label>Sell<input id="psell" type="number" step="0.01"></label><label>Cross References<input id="cross"></label></div><div class="actions"><button id="researchPart" class="btn primary">Parts Research Checklist</button><button id="savePart" class="btn ok">Save Part</button><button id="partsToQuote" class="btn">Send Parts To Quote</button></div><div id="partOut" class="notice" style="display:none"></div>`+list('parts'))},
kits(){const job=['Wheel Seal Job','Clutch Job','Water Pump Job','King Pin Job','Brake Job','Air Bag Job','Starter Job','Alternator Job'];return module('PM / Filter Kits',`<div class="two"><div><h3>PM Filter Kit</h3><div class="form one"><label>VIN<input id="kitVin" value="${esc(st.active.vin)}"></label><label>Engine<select id="kitEngine"><option>Cummins ISX/X15</option><option>Detroit DD13/DD15</option><option>PACCAR MX</option><option>Volvo D13</option><option>International A26</option><option>Other</option></select></label></div><button id="pmKit" class="btn primary full">Build PM Kit</button></div><div><h3>Job Parts Kit</h3><div class="form one"><label>Job Type<select id="jobType">${job.map(j=>`<option>${j}</option>`).join('')}</select></label><label>VIN / Unit<input id="jobVin" value="${esc(st.active.vin||st.active.unit)}"></label></div><button id="jobKit" class="btn primary full">Build Job Kit</button></div></div><div id="kitOut" class="records"></div>`+list('kits'))},
ocr(){return module('OCR Intake',`<p class="muted">Paste OCR text from a photo for now, or use voice notes. The app extracts VINs, part numbers, and prices, then sends them to quote/invoice/parts.</p><textarea id="ocrText" placeholder="Paste receipt, invoice, part label, VIN plate, or handwritten note text here"></textarea><div class="actions"><button id="voice" class="btn">Voice Note</button><button id="readOcr" class="btn primary">Read OCR Text</button><button id="ocrParts" class="btn">Send To Parts</button><button id="ocrQuote" class="btn">Send To Quote</button><button id="ocrInvoice" class="btn">Send To Invoice</button></div><div id="ocrOut" class="records"></div>`+list('ocr'))},
customers(){return simpleRecord('customers','Customers',['name','phone','email','address','notes'])},
units(){return simpleRecord('units','Trucks / Equipment',['unit','vin','engine','transmission','mileage','notes'])},
quotes(){return docPage('quotes','Quotes','quoteToWo','Convert Latest Quote To Work Order')},
workorders(){return docPage('workorders','Work Orders','woToInv','Convert Latest Work Order To Invoice')},
invoices(){return docPage('invoices','Invoices','','')+module('Signature Capture',`<canvas id="sig" class="sig"></canvas><div class="actions"><button id="clearSig" class="btn">Clear</button><button id="saveSig" class="btn ok">Save Signature To Latest Invoice</button></div>`)},
clock(){return module('Time Clock',`<div class="grid">${['A','B','C'].map(k=>{let c=st.clocks[k],sec=Number(c.sec||0)+(c.run?Math.floor((Date.now()-c.start)/1000):0);return `<div class="card"><label>Clock ${k}<input class="clockName" data-clock="${k}" value="${esc(c.name)}"></label><div class="money">${fmt(sec)}</div><div class="actions"><button class="btn ok" data-start="${k}">Start</button><button class="btn" data-pause="${k}">Pause</button><button class="btn danger" data-stop="${k}">Stop</button></div></div>`}).join('')}</div>`)},
schedule(){return simpleRecord('schedule','Schedule',['date','customer','unit','job','notes'])},
pm(){return simpleRecord('pm','PM Tracking',['unit','vin','service','due','mileage','notes'])},
gps(){return module('GPS Service Calls',`<div class="actions"><button id="gps" class="btn primary">Get Current Location</button><button id="savePin" class="btn ok">Save Pin</button></div><div id="gpsOut" class="records"></div>`+list('pins'))},
memory(){return simpleRecord('memory','Repair Memory',['unit','vin','repair','parts','result','notes'])},
fault(){return module('Fault Doctor',`<div class="notice"><h2>Under Construction</h2><p>Fault Doctor is intentionally parked for now. Fault notes should be saved inside Work Orders or Repair Memory until this module is ready.</p></div>`)},
settings(){return module('Settings',`<div class="form"><label>Shop<input id="set_shop" value="${esc(st.settings.shop)}"></label><label>Phone<input id="set_phone" value="${esc(st.settings.phone)}"></label><label>Labor Rate<input id="set_laborRate" type="number" value="${esc(st.settings.laborRate)}"></label><label>Service Call<input id="set_serviceCall" type="number" value="${esc(st.settings.serviceCall)}"></label><label>Tax %<input id="set_tax" type="number" value="${esc(st.settings.tax)}"></label><label>Parts Markup %<input id="set_markup" type="number" value="${esc(st.settings.markup)}"></label><label>Theme<select id="set_theme">${THEMES.map(t=>`<option ${st.theme===t?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="actions"><button id="saveSettings" class="btn primary">Save Settings</button><button id="backup" class="btn">Download Backup</button><button id="clear" class="btn danger">Clear Local Data</button></div><div class="notice"><b>Locked scope:</b> shop-only scope with no separate side-app, no finance dashboard, no chat screen. Utility intelligence may assist quote/invoice wording, OCR cleanup, VIN extraction, and parts research inside tools only.</div>`)}}
function module(title,body){return `<section class="layout"><aside class="side no-print">${modules.map(m=>`<button data-nav="${m[0]}" class="btn ${st.view===m[0]?'active':''}">${m[2]}</button>`).join('')}</aside><section class="module"><h2>${title}</h2>${body}</section></section>`}
function list(key){let arr=st[key]||[];return `<div class="records">${arr.slice(0,10).map(x=>`<div class="record"><div class="record-head"><div><b>${esc(x.name||x.unit||x.vin||x.partNumber||x.desc||x.customer||x.job||x.repair||x.service||x.date)}</b><p class="muted">${esc(x.notes||x.desc||x.vin||'')}</p></div><button class="btn danger" data-del="${key}" data-id="${x.id}">Delete</button></div></div>`).join('')}</div>`}
function simpleRecord(key,title,fields){return module(title,`<div class="form">${fields.map(f=>`<label>${f.toUpperCase()}${f==='notes'?`<textarea id="${key}_${f}"></textarea>`:`<input id="${key}_${f}">`}</label>`).join('')}</div><div class="actions"><button class="btn primary" data-save="${key}">Save ${title}</button></div>`+list(key))}
function docPage(key,title,convId,convText){return module(title,`<div class="form"><label>Customer<input id="${key}_customer" value="${esc(st.active.customer)}"></label><label>Unit / VIN<input id="${key}_unit" value="${esc(st.active.unit||st.active.vin)}"></label><label>Labor Hours<input id="${key}_hours" type="number" step="0.1"></label><label>Labor Rate<input id="${key}_rate" type="number" value="${esc(st.settings.laborRate)}"></label><label>Parts Total<input id="${key}_parts" type="number" step="0.01"></label><label>Description<input id="${key}_desc"></label><label>Notes<textarea id="${key}_notes"></textarea></label></div><div class="actions"><button class="btn primary" data-doc="${key}">Save ${title}</button>${convId?`<button id="${convId}" class="btn ok">${convText}</button>`:''}<button class="btn" onclick="window.print()">Print</button></div>`+list(key))}
function vinDecode(v){v=String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');let map={A:2010,B:2011,C:2012,D:2013,E:2014,F:2015,G:2016,H:2017,J:2018,K:2019,L:2020,M:2021,N:2022,P:2023,R:2024,S:2025,T:2026,V:2027,W:2028,X:2029,Y:2030,'1':2001,'2':2002,'3':2003,'4':2004,'5':2005,'6':2006,'7':2007,'8':2008,'9':2009};return {vin:v,ok:v.length===17,year:map[v[9]]||'Unknown',wmi:v.slice(0,3),serial:v.slice(11)}}
const kits={
 'Wheel Seal Job':['Wheel seal','Inner bearing','Outer bearing','Hub cap gasket','Hub oil','Cotter pin / hardware'],
 'Clutch Job':['Clutch assembly','Pilot bearing','Release bearing','Flywheel bolts','Input shaft kit if needed','Transmission fluid as needed'],
 'Water Pump Job':['Water pump','Gasket / O-ring','Belt','Coolant','Thermostats if needed','Hose clamps'],
 'King Pin Job':['King pin kit','Bushings','Thrust bearings','Shims','Seals','Grease'],
 'Brake Job':['Brake shoes / pads','Drums / rotors if needed','Hardware kit','S-cam bushings if needed','Slack adjuster if needed'],
 'Air Bag Job':['Air spring','Fittings','Air line repair kit'], 'Starter Job':['Starter','Battery cable ends','Mounting hardware'], 'Alternator Job':['Alternator','Belt','Terminal repair ends']
};
function extract(t){t=String(t||'');return {vins:[...new Set((t.toUpperCase().match(/\b[A-HJ-NPR-Z0-9]{17}\b/g)||[]))],parts:[...new Set((t.toUpperCase().match(/\b[A-Z0-9][A-Z0-9-]{4,24}\b/g)||[]).filter(x=>!/^\d{17}$/.test(x)))],prices:(t.match(/\$?\d+\.\d{2}/g)||[])}}
function saveRecord(key){let o={id:uid(),date:today()};$$(`[id^="${key}_"]`).forEach(i=>o[i.id.replace(key+'_','')]=i.value);st[key].unshift(o);st.sync.unshift({type:key,id:o.id,date:today()});save();toast('Saved');render()}
function saveDoc(key){let o={id:uid(),date:today()};['customer','unit','hours','rate','parts','desc','notes'].forEach(f=>o[f]=$(`#${key}_${f}`)?.value||'');let labor=Number(o.hours||0)*Number(o.rate||0),parts=Number(o.parts||0),tax=(labor+parts)*Number(st.settings.tax||0)/100;o.subtotal=labor+parts;o.total=o.subtotal+tax;st[key].unshift(o);st.sync.unshift({type:key,id:o.id,date:today()});save();toast(`${key} saved: ${money(o.total)}`);render()}
function fmt(s){s=Math.floor(s||0);return [s/3600,(s%3600)/60,s%60].map(v=>String(Math.floor(v)).padStart(2,'0')).join(':')}
function bind(){
 $$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));
 $('#decode')&&( $('#decode').onclick=()=>{let d=vinDecode($('#vin').value);$('#vinOut').innerHTML=`<div class="record"><b>${d.ok?'VIN format OK':'VIN needs 17 valid characters'}</b><p>Year: ${esc(d.year)} • WMI: ${esc(d.wmi)} • Serial: ${esc(d.serial)}</p></div>`});
 $('#saveUnit')&&( $('#saveUnit').onclick=()=>{let d=vinDecode($('#vin').value),u={id:uid(),date:today(),unit:$('#unit').value||d.vin,vin:d.vin,customer:$('#customer').value,year:d.year,engine:$('#engine').value,transmission:$('#trans').value,mileage:$('#miles').value,notes:$('#notes').value};st.units.unshift(u);st.active={customer:u.customer,unit:u.unit,vin:u.vin};save();toast('Unit saved');render()});
 $('#vinToParts')&&( $('#vinToParts').onclick=()=>{st.active.vin=$('#vin').value.toUpperCase();save();nav('parts')});
 $('#researchPart')&&( $('#researchPart').onclick=()=>{let e=$('#partOut');e.style.display='block';e.innerHTML='<b>Parts research flow</b><br>1. Confirm VIN/ESN.<br>2. Match OEM number.<br>3. Check supersession.<br>4. Verify fitment and quantity.<br>5. Save part and send to quote/work order.'});
 $('#savePart')&&( $('#savePart').onclick=()=>{let cost=Number($('#pcost').value||0),sell=Number($('#psell').value||0)||cost*(1+Number(st.settings.markup||0)/100);st.parts.unshift({id:uid(),date:today(),vin:$('#partVin').value,engine:$('#partEngine').value,partNumber:$('#pn').value,desc:$('#pdesc').value,qty:Number($('#pqty').value||1),cost,sell,cross:$('#cross').value});save();toast('Part saved');render()});
 $('#partsToQuote')&&( $('#partsToQuote').onclick=()=>{let total=st.parts.reduce((a,p)=>a+(Number(p.sell||0)*Number(p.qty||1)),0);st.quotes.unshift({id:uid(),date:today(),customer:st.active.customer,unit:st.active.unit||st.active.vin,parts:total,total,desc:'Parts quote',notes:st.parts.slice(0,12).map(p=>`${p.qty} x ${p.partNumber||p.desc}`).join('; ')});save();toast('Parts sent to quote');nav('quotes')});
 $('#pmKit')&&( $('#pmKit').onclick=()=>{let items=['Oil filter','Primary fuel filter','Secondary fuel filter','Air filter','Cabin filter if equipped','Crankcase filter if equipped','DEF filter if equipped','Oil/coolant notes'];st.kits.unshift({id:uid(),date:today(),name:'PM Filter Kit',vin:$('#kitVin').value,engine:$('#kitEngine').value,items});$('#kitOut').innerHTML=kitHtml('PM Filter Kit',items);save();});
 $('#jobKit')&&( $('#jobKit').onclick=()=>{let name=$('#jobType').value,items=kits[name]||[];st.kits.unshift({id:uid(),date:today(),name,vin:$('#jobVin').value,items});$('#kitOut').innerHTML=kitHtml(name,items);save();});
 document.addEventListener('click',e=>{let add=e.target.closest('[data-addpart]'); if(add){st.parts.unshift({id:uid(),date:today(),partNumber:'',desc:add.dataset.addpart,qty:1,cost:0,sell:0,cross:''});save();toast('Kit item added to parts')} if(e.target.id==='kitQuote'){let k=st.kits[0];st.quotes.unshift({id:uid(),date:today(),customer:st.active.customer,unit:st.active.unit||k.vin,desc:k.name,parts:0,total:0,notes:k.items.join('; ')});save();toast('Kit sent to quote');nav('quotes')}});
 $('#readOcr')&&( $('#readOcr').onclick=()=>{let x=extract($('#ocrText').value);st.ocr.unshift({id:uid(),date:today(),vin:x.vins[0]||'',parts:x.parts.join(', '),notes:$('#ocrText').value.slice(0,300)});$('#ocrOut').innerHTML=`<div class="record"><b>Extracted</b><p>VINs: ${esc(x.vins.join(', ')||'none')}<br>Parts: ${esc(x.parts.slice(0,12).join(', ')||'none')}<br>Prices: ${esc(x.prices.join(', ')||'none')}</p></div>`;save()});
 $('#voice')&&( $('#voice').onclick=()=>{let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('Voice requires supported browser and HTTPS');let r=new R();r.onresult=e=>{$('#ocrText').value += ' '+e.results[0][0].transcript};r.start()});
 $('#ocrParts')&&( $('#ocrParts').onclick=()=>{extract($('#ocrText').value).parts.forEach(p=>st.parts.unshift({id:uid(),date:today(),partNumber:p,desc:'OCR extracted part',qty:1,cost:0,sell:0,cross:''}));save();toast('OCR sent to parts');nav('parts')});
 $('#ocrQuote')&&( $('#ocrQuote').onclick=()=>{let x=extract($('#ocrText').value);st.quotes.unshift({id:uid(),date:today(),customer:st.active.customer,unit:x.vins[0]||st.active.unit,desc:'OCR imported quote',parts:0,total:0,notes:$('#ocrText').value.slice(0,600)});save();nav('quotes')});
 $('#ocrInvoice')&&( $('#ocrInvoice').onclick=()=>{let x=extract($('#ocrText').value);st.invoices.unshift({id:uid(),date:today(),customer:st.active.customer,unit:x.vins[0]||st.active.unit,desc:'OCR imported invoice',parts:0,total:0,notes:$('#ocrText').value.slice(0,600)});save();nav('invoices')});
 $$('[data-save]').forEach(b=>b.onclick=()=>saveRecord(b.dataset.save)); $$('[data-doc]').forEach(b=>b.onclick=()=>saveDoc(b.dataset.doc));
 $('#quoteToWo')&&( $('#quoteToWo').onclick=()=>{let q=st.quotes[0]; if(!q)return toast('Create quote first');st.workorders.unshift({...q,id:uid(),quoteId:q.id,status:'Open',date:today()});save();nav('workorders')});
 $('#woToInv')&&( $('#woToInv').onclick=()=>{let w=st.workorders[0]; if(!w)return toast('Create work order first');st.invoices.unshift({...w,id:uid(),workorderId:w.id,status:'Invoice',date:today()});save();nav('invoices')});
 $$('[data-del]').forEach(b=>b.onclick=()=>{st[b.dataset.del]=st[b.dataset.del].filter(x=>x.id!==b.dataset.id);save();render()});
 $$('.clockName').forEach(i=>i.onchange=()=>{st.clocks[i.dataset.clock].name=i.value;save()}); $$('[data-start]').forEach(b=>b.onclick=()=>{let c=st.clocks[b.dataset.start]; if(!c.run){c.run=true;c.start=Date.now();save();render()}}); $$('[data-pause]').forEach(b=>b.onclick=()=>{let c=st.clocks[b.dataset.pause]; if(c.run){c.sec+=Math.floor((Date.now()-c.start)/1000);c.run=false;c.start=0;save();render()}}); $$('[data-stop]').forEach(b=>b.onclick=()=>{let c=st.clocks[b.dataset.stop];c.sec=0;c.run=false;c.start=0;save();render()});
 $('#gps')&&( $('#gps').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{$('#gpsOut').innerHTML=`<div class="record"><b>Current Location</b><p>${p.coords.latitude}, ${p.coords.longitude}</p></div>`;st._gps={lat:p.coords.latitude,lng:p.coords.longitude}},()=>toast('GPS permission denied')):toast('GPS not supported'));
 $('#savePin')&&( $('#savePin').onclick=()=>{let g=st._gps||{lat:'',lng:''};st.pins.unshift({id:uid(),date:today(),lat:g.lat,lng:g.lng,notes:st.active.customer});save();render()});
 $('#saveSettings')&&( $('#saveSettings').onclick=()=>{Object.keys(st.settings).forEach(k=>{let e=$('#set_'+k); if(e)st.settings[k]=e.type==='number'?Number(e.value):e.value});st.theme=$('#set_theme').value;save();toast('Settings saved');render()});
 $('#backup')&&( $('#backup').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(st,null,2)],{type:'application/json'}));a.download='BA001-backup.json';a.click();URL.revokeObjectURL(a.href)}); $('#clear')&&( $('#clear').onclick=()=>{if(confirm('Clear BA001 local data?')){localStorage.removeItem(STORE);st=structuredClone(base);render()}});
 sigBind();
}
function kitHtml(name,items){return `<div class="record"><div class="record-head"><div><h3>${esc(name)}</h3><div class="kit-list">${items.map(i=>`<div class="kit-item"><b>${esc(i)}</b><button class="btn" data-addpart="${esc(i)}">Add Part</button></div>`).join('')}</div></div></div><div class="actions"><button id="kitQuote" class="btn ok">Add Kit To Quote</button></div></div>`}
function sigBind(){let c=$('#sig'); if(!c)return;let ctx=c.getContext('2d'),draw=false,last=null;function size(){c.width=c.offsetWidth*2;c.height=c.offsetHeight*2;ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.lineCap='round'}function p(e){let r=c.getBoundingClientRect(),x=e.touches?e.touches[0]:e;return{x:(x.clientX-r.left)*c.width/r.width,y:(x.clientY-r.top)*c.height/r.height}}size();c.onpointerdown=e=>{draw=true;last=p(e)};c.onpointermove=e=>{if(!draw)return;let q=p(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(q.x,q.y);ctx.stroke();last=q};c.onpointerup=()=>draw=false;$('#clearSig')&&( $('#clearSig').onclick=()=>ctx.clearRect(0,0,c.width,c.height));$('#saveSig')&&( $('#saveSig').onclick=()=>{if(!st.invoices[0])return toast('Create invoice first');st.invoices[0].signature=c.toDataURL();save();toast('Signature saved')})}
window.addEventListener('error',e=>{console.error(e.message)});setInterval(()=>{if(st.view==='clock')render()},30000);if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});render();
})();
